# ckan-ingestor-rs
#
# Development image used by the Rust GitLab CI job.
FROM rustlang/rust:nightly-slim-2026-09-04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    curl \
    libssl-dev \
    libcurl4-openssl-dev \
    pkg-config \
    sccache \
    && rm -rf /var/lib/apt/lists/*

RUN --toolchain nightly-2026-09-04-aarch64-unknown-linux-gnu rustup component add rustfmt clippy rust-analyzer
