-- +goose Up
CREATE TABLE IF NOT EXISTS alembic_version (version_num varchar(32) NOT NULL PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO alembic_version(version_num) VALUES ('020');
CREATE TABLE IF NOT EXISTS ckan_instance (id char(36) NOT NULL PRIMARY KEY,name varchar(255) NOT NULL UNIQUE,url varchar(512) NOT NULL,last_metadata_synced datetime NULL,dataset_count int NOT NULL DEFAULT 0,resource_count int NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ckan_data_job (id varchar(36) NOT NULL PRIMARY KEY,resource_id varchar(255) NOT NULL,resource_name varchar(512),resource_url text,resource_format varchar(50),status enum('pending','processing','completed','failed','deleted') NOT NULL,idempotency_key varchar(255) NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,started_at datetime,completed_at datetime,dataset_name varchar(512) NOT NULL,instance_id char(36) NOT NULL,ckan_url varchar(512) NOT NULL DEFAULT '',message_topic varchar(255),message_partition int,message_offset bigint,datastore_active tinyint(1) NOT NULL DEFAULT 0,broker_type varchar(32),message_stream varchar(255),KEY ix_ckan_data_job_status(status),KEY ix_ckan_data_job_resource_id(resource_id),KEY ix_job_status_resource(status,resource_id),KEY ix_ckan_data_job_instance_id(instance_id),KEY ix_ckan_data_job_idempotency_key(idempotency_key),CONSTRAINT fk_ckan_data_job_instance_id FOREIGN KEY(instance_id) REFERENCES ckan_instance(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ckan_data_job_result (id varchar(36) NOT NULL PRIMARY KEY,job_id varchar(36) NOT NULL,success tinyint(1) NOT NULL,error_message text,error_trace text,dataset_preview json,rows_processed int,created_at datetime NOT NULL,expected_rows int,resource_size int,encoding varchar(50),status enum('pending','processing','completed','failed','deleted') NOT NULL,KEY ix_ckan_data_job_result_job_id(job_id),FOREIGN KEY(job_id) REFERENCES ckan_data_job(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS csv_hint (resource_id varchar(255) NOT NULL PRIMARY KEY,delimiter varchar(10) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS latest_resource_job (resource_id varchar(255) NOT NULL PRIMARY KEY,latest_job_id char(36) NOT NULL,instance_id char(36) NOT NULL,resource_name varchar(512),resource_url text,resource_format varchar(50),dataset_name varchar(512) NOT NULL,status enum('pending','processing','completed','failed','outdated','deleted') NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,KEY(latest_job_id),KEY ix_latest_resource_job_instance_id(instance_id),FOREIGN KEY(latest_job_id) REFERENCES ckan_data_job(id),FOREIGN KEY(instance_id) REFERENCES ckan_instance(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS last_terminal_status (resource_id varchar(255) NOT NULL PRIMARY KEY,last_terminal_job_id varchar(36) NOT NULL,last_terminal_status enum('completed','failed','deleted') NOT NULL,last_terminal_at datetime NOT NULL,last_successful_job_id varchar(36),KEY(last_terminal_job_id),KEY(last_successful_job_id),FOREIGN KEY(last_terminal_job_id) REFERENCES ckan_data_job(id),FOREIGN KEY(last_successful_job_id) REFERENCES ckan_data_job(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS metadata_sync (id char(36) NOT NULL PRIMARY KEY,instance_id char(36) NOT NULL,start_time datetime NOT NULL,end_time datetime,total_packages int NOT NULL DEFAULT 0,new_datasets int NOT NULL DEFAULT 0,new_resources int NOT NULL DEFAULT 0,updated_datasets int NOT NULL DEFAULT 0,updated_resources int NOT NULL DEFAULT 0,status varchar(20),error_message text,deleted_datasets int NOT NULL DEFAULT 0,deleted_resources int NOT NULL DEFAULT 0,KEY ix_metadata_sync_instance_id(instance_id),FOREIGN KEY(instance_id) REFERENCES ckan_instance(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS resource_metadata_label (id char(36) NOT NULL PRIMARY KEY,resource_id varchar(255) NOT NULL,label varchar(100) NOT NULL,created_at datetime NOT NULL,UNIQUE KEY uq_resource_label(resource_id,label),KEY ix_resource_metadata_label_resource_id(resource_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
SELECT 1;
