image: docker
services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

test:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  variables:
    UV_VERSION: "0.5"
    UV_CACHE_DIR: .uv-cache
    PYTHON_VERSION: "3.12"
    BASE_LAYER: bookworm-slim
    # GitLab CI creates a separate mountpoint for the build directory,
    # so we need to copy instead of using hard links.
    UV_LINK_MODE: copy
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - uv sync
    - uv run ruff check
    - uv run pytest
    - uv cache prune --ci

build:
  stage: build
  script:
    - cd ckan_ingestor
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker buildx build --platform linux/amd64,linux/arm64 --push -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
  rules:
    - if: $CI_COMMIT_BRANCH == $TARGET_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH
      changes:
        - ckan_ingestor/**/*
#
#deploy-ingestor:
#  stage: deploy
#  variables:
#    TARGET_ENV: production
#    TF_ROOT:  "infra"
#    TF_STATE_NAME:  "ingestor"
#    TARGET_BRANCH: main
#  trigger:
#    strategy: depend
#    include:
#      - local: /templates/validate-plan-apply.yml
#        inputs:
#          version: 0.18.0
#          opentofu_version: 1.7.1
#          root_dir: $TF_ROOT
#          state_name: $TF_STATE_NAME
#          stage_validate: build
#          stage_build: build
#          stage_deploy: deploy
#          runner_env: $TARGET_ENV
#          runner_tag: $TARGET_ENV
#  rules:
#    - if: $CI_COMMIT_BRANCH == $TARGET_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH

