version: '3'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS=:9001
    command: server /data
    healthcheck:
      test: "bash -c '[[ \"$(exec 3<>/dev/tcp/localhost/9000 && echo -e '\"'\"'GET /minio/health/live HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n'\"'\"' >&3 && cat <&3 | head -n 1)\" == *\"200 OK\"* ]] || exit 1'"
      interval: 5s
      timeout: 2s
      retries: 15
    networks:
      iceberg_net:
        ipv4_address: 10.5.0.3

  # Create MinIO bucket
  minio-setup:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse/;
      /usr/bin/mc policy set public minio/warehouse/;
      tail -f /dev/null
      "
    networks:
      iceberg_net:

  db:
    image: bitnami/postgresql:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres" ]
      interval: 2s
      timeout: 10s
      retries: 2
    networks:
      iceberg_net:


networks:
  iceberg_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1