[project]
name = "ckan-ingestor"
version = "0.1.0"
description = ""
authors = [{ name = "guilhermecastro", email = "guilherme.castro@protonmail.com" }]
requires-python = ">=3.11.9,<3.13"
readme = "README.md"
dependencies = [
    "pyarrow>=18.0.0,<19",
    "pytest>=8.3.3,<9",
    "pydantic-settings>=2.6.1,<3",
    "dlt[s3,deltalake]>=1.5.0,<2",
    "duckdb>=1.3.0,<2",
    "minio>=7.2.15",
]

[dependency-groups]
dev = [
    "mock>=5.1.0,<6",
    "pytest>=8.3.2,<9",
    "testcontainers[minio, postgres]>=4.10.0,<5",
]

[tool.hatch.build.targets.sdist]
include = ["ckan_ingestor"]

[tool.hatch.build.targets.wheel]
include = ["ckan_ingestor"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
