[pytest]
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    # Suprimir deprecations do testcontainers
    ignore:.*wait_container_is_ready.*:DeprecationWarning:testcontainers.core.waiting_utils
    ignore:.*wait_container_is_ready.*:DeprecationWarning:testcontainers.minio.__init__
    ignore:.*wait_container_is_ready.*:DeprecationWarning:testcontainers.redis.__init__
