connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://10.5.0.4:8080/catalog
iceberg.rest-catalog.warehouse=demo
iceberg.rest-catalog.security=NONE
iceberg.rest-catalog.vended-credentials-enabled=true
s3.region=any
s3.endpoint=http://10.5.0.3:9000
s3.path-style-access=true
fs.native-s3.enabled=true

