apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingestor-orchestrator.fullname" . }}
  labels:
    {{- include "ingestor-orchestrator.labels" . | nindent 4 }}
data:
  INGEST_ORCH_MYSQL_HOST: {{ .Values.mysql.host | quote }}
  INGEST_ORCH_MYSQL_PORT: {{ .Values.mysql.port | quote }}
  INGEST_ORCH_MYSQL_USER: {{ .Values.mysql.user | quote }}
  INGEST_ORCH_MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  INGEST_ORCH_NATS_URL: {{ printf "nats://%s-nats:4222" .Release.Name | quote }}
  INGEST_ORCH_NATS_STREAM: {{ .Values.nats.stream | quote }}
  INGEST_ORCH_NATS_SUBJECT: {{ .Values.nats.subject | quote }}
  INGEST_ORCH_DEBUG: {{ .Values.debug | quote }}
  {{- if .Values.ducklake.dataPath.endpoint }}
  DUCKLAKE_DATA_PATH__ENDPOINT: {{ .Values.ducklake.dataPath.endpoint | quote }}
  {{- end }}
  {{- if .Values.ducklake.dataPath.bucket }}
  DUCKLAKE_DATA_PATH__BUCKET: {{ .Values.ducklake.dataPath.bucket | quote }}
  {{- end }}
  {{- if .Values.ducklake.dataPath.urlStyle }}
  DUCKLAKE_DATA_PATH__URL_STYLE: {{ .Values.ducklake.dataPath.urlStyle | quote }}
  {{- end }}
