apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingestor-orchestrator.fullname" . }}
  labels:
    {{- include "ingestor-orchestrator.labels" . | nindent 4 }}
data:
  INGEST_ORCH_MYSQL_HOST: {{ .Values.mysql.host | quote }}
  INGEST_ORCH_MYSQL_PORT: {{ .Values.mysql.port | quote }}
  INGEST_ORCH_MYSQL_USER: {{ .Values.mysql.user | quote }}
  INGEST_ORCH_MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  INGEST_ORCH_KAFKA_BOOTSTRAP_SERVERS: {{- if .Values.kafka.deploy }} {{ printf "%s-kafka-bootstrap:9092" (include "ingestor-orchestrator.fullname" .) | quote }}{{- else }} {{ .Values.kafka.bootstrapServers | quote }}{{- end }}
  INGEST_ORCH_KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
  INGEST_ORCH_KAFKA_TOPIC_RETRY: {{ .Values.kafka.topicRetry | quote }}
  INGEST_ORCH_KAFKA_GROUP_ID: {{ .Values.kafka.groupId | quote }}
  INGEST_ORCH_DEBUG: {{ .Values.debug | quote }}
  {{- if .Values.ducklake.dataPath.endpoint }}
  DUCKLAKE_DATA_PATH__ENDPOINT: {{ .Values.ducklake.dataPath.endpoint | quote }}
  {{- end }}
  {{- if .Values.ducklake.dataPath.bucket }}
  DUCKLAKE_DATA_PATH__BUCKET: {{ .Values.ducklake.dataPath.bucket | quote }}
  {{- end }}
  {{- if .Values.ducklake.dataPath.urlStyle }}
  DUCKLAKE_DATA_PATH__URL_STYLE: {{ .Values.ducklake.dataPath.urlStyle | quote }}
  {{- end }}
