apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingestor-orchestrator.fullname" . }}
  labels:
    {{- include "ingestor-orchestrator.labels" . | nindent 4 }}
data:
  INGEST_ORCH_MYSQL_HOST: {{ .Values.mysql.host | quote }}
  INGEST_ORCH_MYSQL_PORT: {{ .Values.mysql.port | quote }}
  INGEST_ORCH_MYSQL_USER: {{ .Values.mysql.user | quote }}
  INGEST_ORCH_MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  INGEST_ORCH_IGGY_ADDRESS: {{ .Values.iggy.address | quote }}
  INGEST_ORCH_IGGY_USERNAME: {{ .Values.iggy.username | quote }}
  INGEST_ORCH_IGGY_STREAM: {{ .Values.iggy.stream | quote }}
  INGEST_ORCH_IGGY_TOPIC: {{ .Values.iggy.topic | quote }}
  INGEST_ORCH_IGGY_TOPIC_RETRY: {{ .Values.iggy.topicRetry | quote }}
  INGEST_ORCH_IGGY_TOPIC_RESULTS: {{ .Values.iggy.topicResults | quote }}
  INGEST_ORCH_IGGY_GROUP_ID: {{ .Values.iggy.groupId | quote }}
  INGEST_ORCH_IGGY_RESULT_GROUP_ID: {{ .Values.iggy.resultGroupId | quote }}
  INGEST_ORCH_IGGY_PARTITIONS: {{ .Values.iggy.partitions | quote }}
  INGEST_ORCH_DEBUG: {{ .Values.debug | quote }}
  DUCKLAKE_DATABASE: {{ .Values.ducklake.database | quote }}
  {{- if .Values.ducklake.dataPath.endpoint }}
  DUCKLAKE_DATA_PATH__ENDPOINT: {{ .Values.ducklake.dataPath.endpoint | quote }}
  {{- end }}
  {{- if .Values.ducklake.dataPath.bucket }}
  DUCKLAKE_DATA_PATH__BUCKET: {{ .Values.ducklake.dataPath.bucket | quote }}
  {{- end }}
  {{- if .Values.ducklake.dataPath.urlStyle }}
  DUCKLAKE_DATA_PATH__URL_STYLE: {{ .Values.ducklake.dataPath.urlStyle | quote }}
  {{- end }}
