{{- if .Values.kafka.deploy }}
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ include "ingestor-orchestrator.fullname" . }}-kafka
  labels:
    {{- include "ingestor-orchestrator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
  annotations:
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.strimzi.version | quote }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: {{ min 3 .Values.kafka.strimzi.replicas }}
      transaction.state.log.replication.factor: {{ min 3 .Values.kafka.strimzi.replicas }}
      transaction.state.log.min.isr: {{ min 2 .Values.kafka.strimzi.replicas }}
      default.replication.factor: {{ min 3 .Values.kafka.strimzi.replicas }}
      min.insync.replicas: {{ min 2 .Values.kafka.strimzi.replicas }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    {{- include "ingestor-orchestrator.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ include "ingestor-orchestrator.fullname" . }}-kafka
spec:
  replicas: {{ .Values.kafka.strimzi.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: {{ .Values.kafka.strimzi.storage.type }}
  resources:
    {{- toYaml .Values.kafka.strimzi.resources | nindent 4 }}
{{- end }}
