{{- if .Values.kafka.topics.autocreate }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafka.topic | replace "." "-" | replace "_" "-" }}
  labels:
    {{- include "ingestor-orchestrator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  topicName: {{ .Values.kafka.topic }}
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafka.topicRetry | replace "." "-" | replace "_" "-" }}
  labels:
    {{- include "ingestor-orchestrator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  topicName: {{ .Values.kafka.topicRetry }}
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
{{- end }}
