[package]
name = "message_processor"
version = "0.1.0"
edition = "2024"

[features]
test-support = []

[dependencies]
tokio = { version = "1.0", features = ["rt", "sync", "macros"] }
anyhow = "1.0"
futures = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
async-stream = "0.3"
