services:

  pulsar:
    image: registry.gitlab.com/pedalin/pulsar-docker-image:pulsar-pedalin-3.3.0
    container_name: pulsar
    command: ['bin/pulsar', 'standalone']
    user: root
    ports:
      - 4181:4181
    environment:
      PULSAR_MEM: '-Xms1g -Xmx1g -XX:MaxDirectMemorySize=2g'
      PULSAR_STANDALONE_USE_ZOOKEEPER: 1
    networks:
      iceberg_net:
    volumes:
      - ./pulsar/bookeeper.conf:/pulsar/conf/bookeeper.conf
      # - ./pulsar/functions_worker.yml:/pulsar/conf/functions_worker.yml
      - ./pulsar/lake_house.json:/pulsar/lake_house.json
  
  trino:
    image: trinodb/trino
    container_name: trino
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - ./trino/iceberg.properties:/etc/trino/catalog/iceberg.properties
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-admin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-password}
      - AWS_REGION=us-east-1 

  xtable:
    image: registry.gitlab.com/pedalin/xtable-docker-image:5bf38428      
    container_name: xtable
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - ./xtable:/xtable
    command: ["--datasetConfig", "/xtable/config.yml", "--hadoopConfig", "/xtable/core-site.xml", "--icebergCatalogConfig", "/xtable/catalog.yml"]

  rest:
    image: tabulario/iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-admin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-password}
      - AWS_REGION=us-east-1 
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000

  polaris:
    image: registry.gitlab.com/pedalin/polaris-docker-image:06a9fcb8
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-admin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-password}
      - AWS_REGION=us-east-1    
    networks:
      iceberg_net:
    ports:
      - 8182:8181
    volumes:
    - ./polaris/polaris-server.yml:/app/polaris-server.yml
      
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse/warehouse;
      /usr/bin/mc mb minio/warehouse/warehouse;
      /usr/bin/mc policy set public minio/warehouse/warehouse;
      tail -f /dev/null
      "
networks:
  iceberg_net: