apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingestor-orchestrator-secrets
  namespace: orchestrator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore

  target:
    name: ingestor-orchestrator-csi
    creationPolicy: Owner

  data:
    - secretKey: INGEST_ORCH_MYSQL_PASSWORD
      remoteRef:
        key: ocid1.vaultsecret.oc1.sa-saopaulo-1.amaaaaaax5wnslaatusjvqyo6rtztynq4nvic252z5esfa3fnbqdkf72zt6q

    - secretKey: DUCKLAKE_CATALOG_URI
      remoteRef:
        key: ocid1.vaultsecret.oc1.sa-saopaulo-1.amaaaaaax5wnslaaxrxqe4uxczjpp25c7k3xqjyrbepxoo2a75wltbdabmxa

    - secretKey: DUCKLAKE_DATA_PATH__ACCESS_KEY_ID
      remoteRef:
        key: ocid1.vaultsecret.oc1.sa-saopaulo-1.amaaaaaax5wnslaabscjs2fz7ughgancmrrcw3xmjucbnw7oa57hlto6feiq

    - secretKey: DUCKLAKE_DATA_PATH__SECRET_ACCESS_KEY
      remoteRef:
        key: ocid1.vaultsecret.oc1.sa-saopaulo-1.amaaaaaax5wnslaar5d4iweyebunj6j3aap6i4ozfhsc3q45erktpg6ga52a
