apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingestor-orchestrator-secrets
  namespace: orchestrator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore

  target:
    name: ingestor-orchestrator-csi
    creationPolicy: Owner

  data:
    - secretKey: INGEST_ORCH_MYSQL_PASSWORD
      remoteRef:
        key: mysql-ckan-admin-password

    - secretKey: DUCKLAKE_CATALOG_URI
      remoteRef:
        key: ducklake_catalog_uri

    - secretKey: DUCKLAKE_DATA_PATH__ACCESS_KEY_ID
      remoteRef:
        key: DUCKLAKE_DATA_PATH__ACCESS_KEY_ID

    - secretKey: DUCKLAKE_DATA_PATH__SECRET_ACCESS_KEY
      remoteRef:
        key: DUCKLAKE_DATA_PATH__SECRET_ACCESS_KEY
