[package]
name = "ckan_worker_coordinator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ckan-worker-coordinator"
path = "src/main.rs"

[dependencies]
ckan_ingestor_lib = { path = "../ckan-ingestor-lib" }
ckan_ingestor_worker_lib = { path = "../ckan-ingestor-worker-lib" }
ckan_metadata_ingestor = { path = "../ckan-metadata-ingestor" }
iggy = "=0.10.0"
futures = "0.3"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros", "sync", "signal", "time"] }
serde_json = "1.0"
serde = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
duckdb = { version = "1.5.5" }
rustls = { version = "0.23", features = ["ring"] }
mysql = "26"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
testcontainers = "0.28"
