[package]
name = "ckan_ingestor_consumer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ckan-ingestor-consumer"
path = "src/main.rs"

[dependencies]
ckan_ingestor_lib = { path = "../ckan-ingestor-lib" }
ckan_metadata_ingestor = { path = "../ckan-metadata-ingestor" }
iggy = "=0.10.0"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros", "sync", "signal", "time"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
futures = "0.3"
log = "0.4"
env_logger = "0.11"
duckdb = { version = "1.5.5" }
reqwest = { version = "0.12", features = ["blocking", "json"] }
rustls = { version = "0.23", features = ["ring"] }

[dev-dependencies]
httpmock = "0.7"
testcontainers = "0.28"
